TestPlaneks/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

from .forms import CustomAuthForm

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('datasets/', include('datasets.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(authentication_form=CustomAuthForm), name='login'),
]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datasets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('schema/<int:pk>/', views.SchemaView.as_view(), name='schema'),
    path('schema/add/', views.SchemaCreateView.as_view(), name='create'),
    path('my/', views.DatasetView.as_view(), name='datasets'),
    path('download/<int:dataset_id>/', views.download, name='download'),
]

datasets/models.py
import os

from django.db import models
from django.conf import settings

from TestPlaneks.storage_backends import PrivateMediaStorage


class DataSchema(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=256)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"({self.id}, {self.name}, {self.created_at})"


class SchemaColumn(models.Model):
    class Meta:
        db_table = 'SchemaColumn'
        constraints = [
            models.UniqueConstraint(fields=['data_schema', 'name'], name='unique column in data_schema')
        ]
    FULL_NAME = 'FN'
    JOB = 'JB'
    EMAIL = 'EM'
    PHONE_NUMBER = 'PM'
    DATE = 'DT'
    DATA_TYPES_CHOICES = [
        (FULL_NAME, 'Full name'),
        (JOB, 'Job'),
        (EMAIL, 'Email'),
        (PHONE_NUMBER, 'Phone number'),
        (DATE, 'Date'),
    ]

    id = models.AutoField(primary_key=True)
    data_schema = models.ForeignKey(DataSchema, on_delete=models.CASCADE)

    name = models.CharField(max_length=256)
    order = models.IntegerField()
    data_type = models.CharField(max_length=2, choices=DATA_TYPES_CHOICES, default=FULL_NAME)

    unique_together = ['data_schema', 'name']


class Dataset(models.Model):
    TEMP_DIRECTORY = '/tmp'

    NEW = 'N'
    PROCESSING = 'P'
    READY = 'R'

    STATUS_CHOICES = [
        (NEW, 'New'),
        (PROCESSING, 'Processing'),
        (READY, 'Ready'),
    ]

    SEMICOLON = ';'
    COMMA = ','
    BAR = ','
    COLON = ':'
    TAB = '\t'
    SPACE = ' '

    DELIMITER_CHOICES = [
        (SEMICOLON, 'Semicolon (;)'),
        (COMMA, 'Comma (,)'),
        (BAR, 'Bar (|)'),
        (COLON, 'Colon (:)'),
        (TAB, 'Tab (\\t)'),
        (SPACE, 'Space ( )'),
    ]

    QUOTE = "'"
    DOUBLE_QUOTES = '"'

    QUOTE_CHOICES = [
        (QUOTE, 'Quote (\')'),
        (DOUBLE_QUOTES, 'Double quotes (")'),
    ]

    id = models.AutoField(primary_key=True)
    data_schema = models.ForeignKey(DataSchema, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=NEW)

    count = models.IntegerField(default=100)
    delimiter = models.CharField(max_length=1, choices=DELIMITER_CHOICES, default=SEMICOLON)
    quote_char = models.CharField(max_length=1, choices=QUOTE_CHOICES, default=DOUBLE_QUOTES)

    file = models.FileField(storage=PrivateMediaStorage(), default=None)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def is_ready(self):
        return self.status == self.READY

TestPlaneks/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))

datasets/forms.py
from django import forms

from .models import DataSchema, SchemaColumn, Dataset


from django.forms.models import inlineformset_factory

ColumnFormset = inlineformset_factory(
    DataSchema, SchemaColumn,
    fields=('order', 'name', 'data_type'),
    extra=0,
    can_delete=False,
    widgets={
        'order': forms.NumberInput(attrs={
            'required': True,
            'readonly': True,
            'value': 1,
            'class': 'form-control'
        }),
        'name': forms.TextInput(attrs={
            'class': 'form-control',
            'required': True
        }),
        'data_type': forms.Select(attrs={
            'class': 'form-select',
            'required': True
        }),
    },
    min_num=1
)


class DatasetForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['count', 'delimiter', 'quote_char']

        widgets = {
            'count': forms.NumberInput(attrs={
                'required': True,
                'class': 'form-control',
                'min': 1,
                'max': 100000
            }),
            'delimiter': forms.Select(attrs={
                'class': 'form-select',
                'required': True
            }),
            'quote_char': forms.Select(attrs={
                'class': 'form-select',
                'required': True
            }),
        }

TestPlaneks/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

datasets/views.py
from django.urls import reverse
from django.views import generic
from django.http import Http404, FileResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .tasks import test
from .models import DataSchema, Dataset
from .forms import ColumnFormset, DatasetForm


class HomeView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5
    template_name = 'home.html'
    context_object_name = 'schemas'

    def get_queryset(self):
        return DataSchema.objects.\
            filter(created_by=self.request.user).\
            order_by('-created_at')


class SchemaView(LoginRequiredMixin, generic.FormView, generic.DetailView):
    template_name = 'schema.html'

    model = DataSchema
    queryset = DataSchema.objects.prefetch_related('schemacolumn_set').order_by('schemacolumn__order')

    form_class = DatasetForm

    def get_object(self, queryset=None):
        obj = super(SchemaView, self).get_object(queryset=queryset)
        if obj.created_by != self.request.user:
            raise Http404()
        return obj

    def get_success_url(self):
        return reverse('datasets')

    def get_context_data(self, **kwargs):
        context = super(SchemaView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.data_schema = self.object
        form.instance.created_by = self.request.user
        form.save()
        test.delay(form.instance.id)
        return super(SchemaView, self).form_valid(form)


class SchemaCreateView(LoginRequiredMixin, generic.CreateView):
    model = DataSchema
    template_name = 'create.html'
    fields = ['name']

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["columns"] = ColumnFormset(self.request.POST)
        else:
            data["columns"] = ColumnFormset()
        return data

    def form_valid(self, form):
        form.instance.created_by = self.request.user

        context = self.get_context_data()
        columns = context["columns"]

        if columns.is_valid():
            self.object = form.save()
            columns.instance = self.object
            columns.save()
        else:
            form.add_error(None, columns.errors)
            return super().form_invalid(form)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


class DatasetView(LoginRequiredMixin, generic.ListView):
    template_name = 'datasets.html'
    context_object_name = 'datasets'

    def get_queryset(self):
        return Dataset.objects.\
            select_related('data_schema').\
            filter(created_by=self.request.user).\
            order_by('-created_at')


@login_required()
def download(request, dataset_id):
    dataset = get_object_or_404(Dataset, pk=dataset_id)

    if dataset.created_by != request.user:
        raise Http404('File not found')

    return redirect(dataset.file.url)

datasets/templates/create.html
{% extends "base.html" %}

{% block title %}Create schema{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}

        <div class="row  align-items-end">
            <div class="col col-sm-10">
                <h1>New data schema</h1>
            </div>
            <div class="col col-sm-2">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </div>
        <div class="mb-3 row align-items-center">
            <div class="col-auto">
                <label for="{{ form.name.id_for_label }}" class="form-label">Schema name:</label>
            </div>
            <div class="col-auto">
                {{ form.name }}
            </div>
{#            <div class="col-auto">#}
{#                <span id="passwordHelpInline" class="form-text">#}
{#                    Only latin letters or numbers#}
{#                </span>#}
{#            </div>#}
        </div>
        {% for error in form.name.errors %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}

        <h3>Schema columns:</h3>

        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}

        {{ columns.management_form }}
        <div id="columns">
        {% for col in columns %}
            <div class="mb-3 row align-items-end">
                <div class="col-1">
                    <label for="{{ col.order.id_for_label }}" class="form-label">Order</label>
                    {{col.order}}
                </div>
                <div class="col">
                    <label for="{{ col.name.id_for_label }}" class="form-label">Column name</label>
                    {{col.name}}
                </div>
                <div class="col">
                    <label for="{{ col.data_type.id_for_label }}" class="form-label">Type</label>
                    {{col.data_type}}
                </div>
                <div class="col">
                    <button type="button" class="btn btn-outline-primary me-2" id="set-{{ forloop.counter0 }}-up">
                        UP
                    </button>
                    <button type="button" class="btn btn-outline-primary me-2" id="set-{{ forloop.counter0 }}-down">
                        DOWN
                    </button>
                    <button type="button" class="btn btn-outline-danger" id="set-{{ forloop.counter0 }}-delete">
                        Delete
                    </button>
                </div>
            </div>
        {% endfor %}
        </div>

        <div  class="mb-3">
            <button id="add_column" type="button" class="btn btn-success">Add column</button>
        </div>
    </form>
{% endblock %}


{% block scripts %}
    <script>
        "use strict";

        let totalForms = document.querySelector("#id_schemacolumn_set-TOTAL_FORMS");
        const MIN_NUM_FORMS = parseInt(document.getElementById('id_schemacolumn_set-MIN_NUM_FORMS').value);

        function getOrder(column_div) {
            return column_div.firstElementChild.firstElementChild.nextElementSibling;
        }

        function getName(column_div) {
            return column_div.firstElementChild.nextElementSibling.firstElementChild.nextElementSibling;
        }

        function getType(column_div) {
            return column_div.firstElementChild.nextElementSibling.nextElementSibling.firstElementChild.nextElementSibling;
        }

        function setOrderValue(column_div, new_value) {
            let order = getOrder(column_div);
            order.value = new_value;
        }

        function getOrderValue(column_div) {
            let order = getOrder(column_div);
            return order.value;
        }

        function resetColumnIds(item, id) {
            const formRegex = RegExp(`set-(\\d){1}-`, 'g');
            item.innerHTML = item.innerHTML.replace(formRegex, `set-${id}-`);
        }

        function deleteColumn(col_div) {
            if (parseInt(totalForms.value) === MIN_NUM_FORMS) {
                return
            }

            let next_div = col_div.nextElementSibling;

            col_div.parentNode.removeChild(col_div);
            totalForms.setAttribute('value', document.getElementById('columns').childElementCount);

            let new_order, name, type_;
            while (next_div  !== null) {
                new_order = getOrderValue(next_div) - 1;
                name = getName(next_div).value;
                type_ = getType(next_div).value;

                resetColumnIds(next_div, new_order - 1);

                setOrderValue(next_div, new_order);
                getName(next_div).value = name;
                getType(next_div).value = type_;

                next_div = next_div.nextElementSibling;
            }
        }

        function swapColumn(col1, col2) {
            let name1 = getName(col1).value;
            let type1 = getType(col1).value;

            getName(col1).value = getName(col2).value;
            getType(col1).value = getType(col2).value;

            getName(col2).value = name1;
            getType(col2).value = type1;
        }

        function moveColumnUp(col_div) {
            let prev_div = col_div.previousElementSibling;
            if (prev_div !== null) {
                swapColumn(prev_div, col_div);
            }
        }

        function moveColumnDown(col_div) {
            let next_div = col_div.nextElementSibling;
            if (next_div !== null) {
                swapColumn(col_div, next_div);
            }
        }

        document.getElementById("add_column").onclick = function() {
            let columns = document.getElementById('columns');
            let new_column = columns.firstElementChild.cloneNode(true);
            const columns_count = document.getElementById('columns').childElementCount;

            columns.appendChild(new_column);
            totalForms.setAttribute('value', columns_count + 1);

            resetColumnIds(new_column, columns_count);
            setOrderValue(new_column, columns_count + 1);

            document.getElementById(`set-${columns_count}-delete`).onclick = function () {
                deleteColumn(this.parentNode.parentNode);
            }
            document.getElementById(`set-${columns_count}-up`).onclick = function () {
                moveColumnUp(this.parentNode.parentNode);
            }
            document.getElementById(`set-${columns_count}-down`).onclick = function () {
                moveColumnDown(this.parentNode.parentNode);
            }
        };

        for (let i = 0; i < totalForms.value; i++) {
            document.getElementById(`set-${i}-delete`).onclick = function () {
                deleteColumn(this.parentNode.parentNode);
            }
            document.getElementById(`set-${i}-up`).onclick = function () {
                moveColumnUp(this.parentNode.parentNode);
            }
            document.getElementById(`set-${i}-down`).onclick = function () {
                moveColumnDown(this.parentNode.parentNode);
            }
        }
    </script>
{% endblock %}

datasets/templates/datasets.html
{% extends "base.html" %}

{% block title %}Datasets{% endblock %}

{% block content %}
    {% if datasets %}
        <table class="table">
            <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Schema</th>
              <th scope="col">Status</th>
              <th scope="col">Created</th>
              <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for ds in datasets %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ ds.data_schema.name }}</td>
                  <td>
                      {% if ds.is_ready %}
                        <span class="badge bg-success">{{ ds.get_status_display  }} </span>
                      {% else %}
                        <span class="badge bg-secondary">{{ ds.get_status_display  }} </span>
                      {% endif %}
                  </td>
                  <td>{{ ds.created_at|date:"Y-m-d H:i:s" }}</td>
                  <td>{% if ds.is_ready %}
                      <a href="{% url 'download' ds.id %}"> Download</a>
                  {% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No datasets</p>
    {% endif %}
{% endblock %}

datasets/templates/home.html
{% extends "base.html" %}

{% block title %}Schemas{% endblock %}

{% block content %}
    <div class="row  align-items-end">
        <div class="col col-sm-10">
            <h1>My data schemas:</h1>
        </div>
        <div class="col col-sm-2">
            <a href="{% url 'create' %}" class="btn btn-success">New schema</a>
        </div>
    </div>

    {% if page_obj %}
        <table class="table">
            <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Schema</th>
              <th scope="col">Created</th>
            </tr>
            </thead>
            <tbody>
            {% for schema in page_obj %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td><a href="{% url 'schema' schema.id %}">{{ schema.name }}</a></td>
                  <td>{{ schema.created_at|date:"Y-m-d H:i:s" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link" aria-hidden="true">&laquo;</span></li>
                {% endif %}

                <li class="page-item active"><span class="page-link">{{ page_obj.number }}</span></li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            {{ page_obj.paginator.num_pages }}
                        </a>
                    </li>
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link" aria-hidden="true">&raquo;</span></li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No schemas</p>
    {% endif %}
{% endblock %}

datasets/templates/schema.html
{% extends "base.html" %}

{% block title %}Schema{% endblock %}

{% block content %}
    <section>
        <h1>Data schema "{{dataschema.name}}"</h1>
        <p>Created at: {{dataschema.created_at|date:"Y-m-d H:i:s"}}</p>
        <br>
    </section>

    <section>
        <h3> Columns: </h3>
        <table class="table">
            <thead>
            <tr>
              <th scope="col">Order</th>
              <th scope="col">Name</th>
              <th scope="col">Type</th>
            </tr>
            </thead>
            <tbody>
            {% for column in dataschema.schemacolumn_set.all %}
                <tr>
                  <td>{{ column.order }}</td>
                  <td>{{ column.name }}</td>
                  <td>{{column.get_data_type_display}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
    </section>

    <section>
        <h3> New dataset: </h3>
        <form method="POST">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit" value="Submit" class="btn btn-success">Generate data</button>
        </form>
    </section>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">FakeCSV</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Schemas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'datasets' %}">Datasets</a>
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
              {% if user.is_authenticated %}
                 <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ user.get_username }}
                   </a>
                   <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                     <li><a class="dropdown-item" href="{% url 'logout'%}">Logout</a></li>
                   </ul>
                 </li>
              {% else %}
                 <li class="nav-item"><a class="nav-link" href="{% url 'login'%}">Login</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}
    <h1>Test task</h1>
    <h4>Made by Fedir Yatsenko</h4>
    <p>Code: <a href="https://github.com/FedorYatsenko/TestPlaneks"> https://github.com/FedorYatsenko/TestPlaneks</a></p>
{% endblock %}